//========== Declaration ==========//
#define STATUS_MONITORING 0

#define INVALID_VALUE B1111111
#define INVALID_FLOAT -100000

#define NUMBER_OF_ADDRESSES 11

//** Adress of datas **//
#define ADR_SET_TEMP_HEATER 0
#define ADR_PREV_AIR_TEMP_ROOM 1
#define ADR_ACT_AIR_TEMP_ROOM 2
#define ADR_PREV_AIR_HUMIDITY_ROOM 3
#define ADR_ACT_AIR_HUMIDITY_ROOM 4
#define ADR_PREV_STATUS_HEATER 5
#define ADR_ACT_STATUS_HEATER 6
#define ADR_PREV_AIR_TEMP_OUTSIDE 7
#define ADR_ACT_AIR_TEMP_OUTSIDE 8
#define ADR_PREV_AIR_HUMIDITY_OUTSIDE 9
#define ADR_ACT_AIR_HUMIDITY_OUTSIDE 10

float datas[NUMBER_OF_ADDRESSES];