// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTempSetChange();

float humidity_inside;
float temp_inside;
float temp_outside;
int temp_set;
bool status_heater;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity_inside, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp_inside, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp_outside, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp_set, READWRITE, ON_CHANGE, onTempSetChange);
  ArduinoCloud.addProperty(status_heater, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
